import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./Header";
import Footer from "./components/Footer";
import "@rainbow-me/rainbowkit/styles.css";
import Provider from "./components/dy-provider";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
} from "../lib/dynamic";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "b073a893-929a-4ff4-8bb6-7cd8c8db2721",
          walletConnectors: [EthereumWalletConnectors],
        }}
      >
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </DynamicContextProvider>
    </html>
  );
}
